/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CustomerUpdate,
  GetAllCustomerByPropsParams
} from '../models';





export type postCreateCustomerByCustomerNameResponse200 = {
  data: void
  status: 200
}

export type postCreateCustomerByCustomerNameResponse404 = {
  data: void
  status: 404
}

export type postCreateCustomerByCustomerNameResponseSuccess = (postCreateCustomerByCustomerNameResponse200) & {
  headers: Headers;
};
export type postCreateCustomerByCustomerNameResponseError = (postCreateCustomerByCustomerNameResponse404) & {
  headers: Headers;
};

export type postCreateCustomerByCustomerNameResponse = (postCreateCustomerByCustomerNameResponseSuccess | postCreateCustomerByCustomerNameResponseError)

export const getPostCreateCustomerByCustomerNameUrl = (customerName: string,) => {


  

  return `/customer/create/${customerName}`
}

export const postCreateCustomerByCustomerName = async (customerName: string, options?: RequestInit): Promise<postCreateCustomerByCustomerNameResponse> => {
  
  const res = await fetch(getPostCreateCustomerByCustomerNameUrl(customerName),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postCreateCustomerByCustomerNameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postCreateCustomerByCustomerNameResponse
}
  



export const getPostCreateCustomerByCustomerNameMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>, TError,{customerName: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>, TError,{customerName: string}, TContext> => {

const mutationKey = ['postCreateCustomerByCustomerName'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>, {customerName: string}> = (props) => {
          const {customerName} = props ?? {};

          return  postCreateCustomerByCustomerName(customerName,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostCreateCustomerByCustomerNameMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>>
    
    export type PostCreateCustomerByCustomerNameMutationError = void

    export const usePostCreateCustomerByCustomerName = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>, TError,{customerName: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
        TError,
        {customerName: string},
        TContext
      > => {
      return useMutation(getPostCreateCustomerByCustomerNameMutationOptions(options), queryClient);
    }
    export type getAllCustomerByPropsResponse200 = {
  data: void
  status: 200
}

export type getAllCustomerByPropsResponse404 = {
  data: void
  status: 404
}

export type getAllCustomerByPropsResponseSuccess = (getAllCustomerByPropsResponse200) & {
  headers: Headers;
};
export type getAllCustomerByPropsResponseError = (getAllCustomerByPropsResponse404) & {
  headers: Headers;
};

export type getAllCustomerByPropsResponse = (getAllCustomerByPropsResponseSuccess | getAllCustomerByPropsResponseError)

export const getGetAllCustomerByPropsUrl = (params?: GetAllCustomerByPropsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/customer/get_all?${stringifiedParams}` : `/customer/get_all`
}

export const getAllCustomerByProps = async (params?: GetAllCustomerByPropsParams, options?: RequestInit): Promise<getAllCustomerByPropsResponse> => {
  
  const res = await fetch(getGetAllCustomerByPropsUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllCustomerByPropsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllCustomerByPropsResponse
}
  




export const getGetAllCustomerByPropsQueryKey = (params?: GetAllCustomerByPropsParams,) => {
    return [
    `/customer/get_all`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllCustomerByPropsQueryOptions = <TData = Awaited<ReturnType<typeof getAllCustomerByProps>>, TError = void>(params?: GetAllCustomerByPropsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllCustomerByPropsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllCustomerByProps>>> = ({ signal }) => getAllCustomerByProps(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllCustomerByPropsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllCustomerByProps>>>
export type GetAllCustomerByPropsQueryError = void


export function useGetAllCustomerByProps<TData = Awaited<ReturnType<typeof getAllCustomerByProps>>, TError = void>(
 params: undefined |  GetAllCustomerByPropsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomerByProps>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomerByProps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCustomerByProps<TData = Awaited<ReturnType<typeof getAllCustomerByProps>>, TError = void>(
 params?: GetAllCustomerByPropsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomerByProps>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomerByProps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllCustomerByProps<TData = Awaited<ReturnType<typeof getAllCustomerByProps>>, TError = void>(
 params?: GetAllCustomerByPropsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllCustomerByProps<TData = Awaited<ReturnType<typeof getAllCustomerByProps>>, TError = void>(
 params?: GetAllCustomerByPropsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllCustomerByProps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllCustomerByPropsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type postUpdateCustomerResponse200 = {
  data: void
  status: 200
}

export type postUpdateCustomerResponse404 = {
  data: void
  status: 404
}

export type postUpdateCustomerResponseSuccess = (postUpdateCustomerResponse200) & {
  headers: Headers;
};
export type postUpdateCustomerResponseError = (postUpdateCustomerResponse404) & {
  headers: Headers;
};

export type postUpdateCustomerResponse = (postUpdateCustomerResponseSuccess | postUpdateCustomerResponseError)

export const getPostUpdateCustomerUrl = () => {


  

  return `/customer/update`
}

export const postUpdateCustomer = async (customerUpdate: CustomerUpdate, options?: RequestInit): Promise<postUpdateCustomerResponse> => {
  
  const res = await fetch(getPostUpdateCustomerUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      customerUpdate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postUpdateCustomerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postUpdateCustomerResponse
}
  



export const getPostUpdateCustomerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUpdateCustomer>>, TError,{data: CustomerUpdate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postUpdateCustomer>>, TError,{data: CustomerUpdate}, TContext> => {

const mutationKey = ['postUpdateCustomer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUpdateCustomer>>, {data: CustomerUpdate}> = (props) => {
          const {data} = props ?? {};

          return  postUpdateCustomer(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostUpdateCustomerMutationResult = NonNullable<Awaited<ReturnType<typeof postUpdateCustomer>>>
    export type PostUpdateCustomerMutationBody = CustomerUpdate
    export type PostUpdateCustomerMutationError = void

    export const usePostUpdateCustomer = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postUpdateCustomer>>, TError,{data: CustomerUpdate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postUpdateCustomer>>,
        TError,
        {data: CustomerUpdate},
        TContext
      > => {
      return useMutation(getPostUpdateCustomerMutationOptions(options), queryClient);
    }
    export type getCustomerByCustomerIdResponse200 = {
  data: void
  status: 200
}

export type getCustomerByCustomerIdResponse404 = {
  data: void
  status: 404
}

export type getCustomerByCustomerIdResponseSuccess = (getCustomerByCustomerIdResponse200) & {
  headers: Headers;
};
export type getCustomerByCustomerIdResponseError = (getCustomerByCustomerIdResponse404) & {
  headers: Headers;
};

export type getCustomerByCustomerIdResponse = (getCustomerByCustomerIdResponseSuccess | getCustomerByCustomerIdResponseError)

export const getGetCustomerByCustomerIdUrl = (customerId: number,) => {


  

  return `/customer/${customerId}`
}

export const getCustomerByCustomerId = async (customerId: number, options?: RequestInit): Promise<getCustomerByCustomerIdResponse> => {
  
  const res = await fetch(getGetCustomerByCustomerIdUrl(customerId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getCustomerByCustomerIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getCustomerByCustomerIdResponse
}
  




export const getGetCustomerByCustomerIdQueryKey = (customerId: number,) => {
    return [
    `/customer/${customerId}`
    ] as const;
    }

    
export const getGetCustomerByCustomerIdQueryOptions = <TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError = void>(customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCustomerByCustomerIdQueryKey(customerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCustomerByCustomerId>>> = ({ signal }) => getCustomerByCustomerId(customerId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(customerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCustomerByCustomerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getCustomerByCustomerId>>>
export type GetCustomerByCustomerIdQueryError = void


export function useGetCustomerByCustomerId<TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError = void>(
 customerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getCustomerByCustomerId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerByCustomerId<TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getCustomerByCustomerId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCustomerByCustomerId<TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCustomerByCustomerId<TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCustomerByCustomerId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCustomerByCustomerIdQueryOptions(customerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type deleteCustomerByCustomerIdResponse200 = {
  data: void
  status: 200
}

export type deleteCustomerByCustomerIdResponse404 = {
  data: void
  status: 404
}

export type deleteCustomerByCustomerIdResponseSuccess = (deleteCustomerByCustomerIdResponse200) & {
  headers: Headers;
};
export type deleteCustomerByCustomerIdResponseError = (deleteCustomerByCustomerIdResponse404) & {
  headers: Headers;
};

export type deleteCustomerByCustomerIdResponse = (deleteCustomerByCustomerIdResponseSuccess | deleteCustomerByCustomerIdResponseError)

export const getDeleteCustomerByCustomerIdUrl = (customerId: number,) => {


  

  return `/customer/${customerId}`
}

export const deleteCustomerByCustomerId = async (customerId: number, options?: RequestInit): Promise<deleteCustomerByCustomerIdResponse> => {
  
  const res = await fetch(getDeleteCustomerByCustomerIdUrl(customerId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: deleteCustomerByCustomerIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteCustomerByCustomerIdResponse
}
  



export const getDeleteCustomerByCustomerIdMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomerByCustomerId>>, TError,{customerId: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomerByCustomerId>>, TError,{customerId: number}, TContext> => {

const mutationKey = ['deleteCustomerByCustomerId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomerByCustomerId>>, {customerId: number}> = (props) => {
          const {customerId} = props ?? {};

          return  deleteCustomerByCustomerId(customerId,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomerByCustomerIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomerByCustomerId>>>
    
    export type DeleteCustomerByCustomerIdMutationError = void

    export const useDeleteCustomerByCustomerId = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomerByCustomerId>>, TError,{customerId: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
        TError,
        {customerId: number},
        TContext
      > => {
      return useMutation(getDeleteCustomerByCustomerIdMutationOptions(options), queryClient);
    }
    