/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BalanceCreateOrUpdateWithoutChangedValue,
  GetAllBalanceParams
} from '../models';





export type postCreateBalanceResponse200 = {
  data: void
  status: 200
}

export type postCreateBalanceResponse404 = {
  data: void
  status: 404
}

export type postCreateBalanceResponseSuccess = (postCreateBalanceResponse200) & {
  headers: Headers;
};
export type postCreateBalanceResponseError = (postCreateBalanceResponse404) & {
  headers: Headers;
};

export type postCreateBalanceResponse = (postCreateBalanceResponseSuccess | postCreateBalanceResponseError)

export const getPostCreateBalanceUrl = () => {


  

  return `/balance`
}

export const postCreateBalance = async (balanceCreateOrUpdateWithoutChangedValue: BalanceCreateOrUpdateWithoutChangedValue, options?: RequestInit): Promise<postCreateBalanceResponse> => {
  
  const res = await fetch(getPostCreateBalanceUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      balanceCreateOrUpdateWithoutChangedValue,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postCreateBalanceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postCreateBalanceResponse
}
  



export const getPostCreateBalanceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateBalance>>, TError,{data: BalanceCreateOrUpdateWithoutChangedValue}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postCreateBalance>>, TError,{data: BalanceCreateOrUpdateWithoutChangedValue}, TContext> => {

const mutationKey = ['postCreateBalance'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCreateBalance>>, {data: BalanceCreateOrUpdateWithoutChangedValue}> = (props) => {
          const {data} = props ?? {};

          return  postCreateBalance(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type PostCreateBalanceMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateBalance>>>
    export type PostCreateBalanceMutationBody = BalanceCreateOrUpdateWithoutChangedValue
    export type PostCreateBalanceMutationError = void

    export const usePostCreateBalance = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCreateBalance>>, TError,{data: BalanceCreateOrUpdateWithoutChangedValue}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCreateBalance>>,
        TError,
        {data: BalanceCreateOrUpdateWithoutChangedValue},
        TContext
      > => {
      return useMutation(getPostCreateBalanceMutationOptions(options), queryClient);
    }
    export type getAllBalanceResponse200 = {
  data: void
  status: 200
}

export type getAllBalanceResponse404 = {
  data: void
  status: 404
}

export type getAllBalanceResponseSuccess = (getAllBalanceResponse200) & {
  headers: Headers;
};
export type getAllBalanceResponseError = (getAllBalanceResponse404) & {
  headers: Headers;
};

export type getAllBalanceResponse = (getAllBalanceResponseSuccess | getAllBalanceResponseError)

export const getGetAllBalanceUrl = (params?: GetAllBalanceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/balance/get-all?${stringifiedParams}` : `/balance/get-all`
}

export const getAllBalance = async (params?: GetAllBalanceParams, options?: RequestInit): Promise<getAllBalanceResponse> => {
  
  const res = await fetch(getGetAllBalanceUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getAllBalanceResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllBalanceResponse
}
  




export const getGetAllBalanceQueryKey = (params?: GetAllBalanceParams,) => {
    return [
    `/balance/get-all`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetAllBalanceQueryOptions = <TData = Awaited<ReturnType<typeof getAllBalance>>, TError = void>(params?: GetAllBalanceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllBalanceQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBalance>>> = ({ signal }) => getAllBalance(params, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBalanceQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBalance>>>
export type GetAllBalanceQueryError = void


export function useGetAllBalance<TData = Awaited<ReturnType<typeof getAllBalance>>, TError = void>(
 params: undefined |  GetAllBalanceParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBalance>>,
          TError,
          Awaited<ReturnType<typeof getAllBalance>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBalance<TData = Awaited<ReturnType<typeof getAllBalance>>, TError = void>(
 params?: GetAllBalanceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBalance>>,
          TError,
          Awaited<ReturnType<typeof getAllBalance>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBalance<TData = Awaited<ReturnType<typeof getAllBalance>>, TError = void>(
 params?: GetAllBalanceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllBalance<TData = Awaited<ReturnType<typeof getAllBalance>>, TError = void>(
 params?: GetAllBalanceParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBalanceQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type getLatestBalanceByCustomerIdResponse200 = {
  data: void
  status: 200
}

export type getLatestBalanceByCustomerIdResponse404 = {
  data: void
  status: 404
}

export type getLatestBalanceByCustomerIdResponseSuccess = (getLatestBalanceByCustomerIdResponse200) & {
  headers: Headers;
};
export type getLatestBalanceByCustomerIdResponseError = (getLatestBalanceByCustomerIdResponse404) & {
  headers: Headers;
};

export type getLatestBalanceByCustomerIdResponse = (getLatestBalanceByCustomerIdResponseSuccess | getLatestBalanceByCustomerIdResponseError)

export const getGetLatestBalanceByCustomerIdUrl = (customerId: number,) => {


  

  return `/balance/latest/${customerId}`
}

export const getLatestBalanceByCustomerId = async (customerId: number, options?: RequestInit): Promise<getLatestBalanceByCustomerIdResponse> => {
  
  const res = await fetch(getGetLatestBalanceByCustomerIdUrl(customerId),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getLatestBalanceByCustomerIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getLatestBalanceByCustomerIdResponse
}
  




export const getGetLatestBalanceByCustomerIdQueryKey = (customerId: number,) => {
    return [
    `/balance/latest/${customerId}`
    ] as const;
    }

    
export const getGetLatestBalanceByCustomerIdQueryOptions = <TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError = void>(customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLatestBalanceByCustomerIdQueryKey(customerId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>> = ({ signal }) => getLatestBalanceByCustomerId(customerId, { signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(customerId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLatestBalanceByCustomerIdQueryResult = NonNullable<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>>
export type GetLatestBalanceByCustomerIdQueryError = void


export function useGetLatestBalanceByCustomerId<TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError = void>(
 customerId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestBalanceByCustomerId<TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLatestBalanceByCustomerId<TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLatestBalanceByCustomerId<TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError = void>(
 customerId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLatestBalanceByCustomerIdQueryOptions(customerId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




