# migrate and generate entity
mage:
  just run 
  just gen-entity

run: 
  RUST_BACKTRACE=1 cargo run

gen-entity:
  DATABASE_URL=sqlite://../app/src-tauri/ams.sqlite?mode=rwc sea-orm-cli generate entity  -o ./../app/src-tauri/src/entity/
