# NOTE: 
# New Flow 
# - delete-database-file
# - run establish_database.rs
# - delete-old-entity
# - gen-entity 
# - run seed_database.rs
# - copy database to api folder

# migrate and generate entity
mage:
  - just delete-database-file
  just delete-old-entity
  cargo run --bin establish_database
  just gen-entity
  # just copy-to-api

delete-old-entity: 
  - rm ../entity/*.rs

# delete-old-entity: 
#   find ./../entity/ -type f \
#     ! -name 'Cargo.toml' \
#     ! -name 'Cargo.lock' \
#     ! -name '.gitignore' \
#     -delete

# will run migration up
run: 
  RUST_BACKTRACE=1 cargo run

gen-entity:
  DATABASE_URL=sqlite://../app/src-tauri/ams.sqlite?mode=rwc \
      sea-orm-cli generate entity  -o ./../entity/ \
      --lib --with-serde both \
      --model-extra-derives 'utoipa::ToSchema' \
      --model-extra-attributes 'serde(rename_all = "camelCase")'

delete-database-file:
  rm ../app/src-tauri/ams.sqlite

copy-to-api: 
  cp ../app/src-tauri/ams.sqlite ../api/

# binary list 
bl: 
  cargo run --bin

tr testName: 
  cargo test {{testName}} -- --nocapture

tl: 
  cargo test -- --list

tf testName: 
  cargo test -- --list | rg -i {{testName}}
