setup: 
  diesel setup

# migration generate 
mg migrationName: 
  diesel migration generate {{migrationName}}

# migration run 
mr: 
  diesel migration run

# binary run
br binaryName *additionalArg: 
  cargo run --bin {{binaryName}} {{additionalArg}}

# binary list
bl : 
  cargo run --bin 

# cargo expand
# just ce schema
ce libPath:
  cargo expand --lib {{libPath}} >> expanded/{{libPath}}_expanded.rs
