/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import type { TransactionType } from './transactionType';

export interface BalanceCreateOrUpdateWithoutChangedValue {
  balance_id: number;
  customer_id: number;
  date: string;
  transaction_type: TransactionType;
  value: number;
}
