/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */

export type GetAllRetrieveDataParams = {
  customer_id?: number;
  start_month?: number;
  end_month?: number;
  year?: number;
};
