/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */

export type GetAllBalanceParams = {
  customer_id?: number;
  year?: number;
  start_date?: string;
  end_date?: string;
};
