/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import type { Customer } from "./customer";
import type { Price } from "./price";

export type RetrieveDataWithCustomerAndPrice = {
  amount: number;
  customer: Customer;
  customer_id: number;
  date: string;
  is_paid: boolean;
  price: Price;
  price_id: number;
  retrieve_data_id: number;
};
