// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { TransactionType } from "./TransactionType";

export type Balance = { balance_id: number, customer_id: number, value: number, date: Date, transaction_type: TransactionType, customer: Customer, };
