// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BalanceWithCustomer } from "./BalanceWithCustomer";
import type { RetrieveDataWithCustomerAndPrice } from "./RetrieveDataWithCustomerAndPrice";

export type BillingInfoWithBalance = { from: Date, to: Date, retrieve_data: Array<RetrieveDataWithCustomerAndPrice>, balance: BalanceWithCustomer, paid_bill: number, paid_total_amount: number, unpaid_bill: number, unpaid_total_amount: number, bill: number, amount: number, };
