// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BillingUpdate = { billing_id: number, customer_id: number, date: Date, from: Date, to: Date, };
