// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BillingInfoGetAllProps = { customer_id: number | null, year: number | null, month: number | null, from: Date, to: Date, };
