// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BillingRetrieveDataWithBillAndAmount = { billing_retrieve_data_id: number, billing_id: number, retrieve_data_id: number, from: Date, to: Date, bill: number, amount: number, };
