// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Customer = { customer_id: number, customer_name: string, is_active: boolean, is_admin: boolean, created_date: Date, updated_date: Date, };
