// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataRecordValueType } from "./DataRecordValueType";

export type DataRecord<KEY> = { data_record_id: number, key: KEY, date: Date, value: DataRecordValueType, };
