// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetrieveDataGetAllProps = { customer_id: number | null, start_month?: number, end_month?: number, year: number | null, };
