// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { Price } from "./Price";

export type RetrieveData = { retrieve_data_id: number, customer_id: number, price_id: number, amount: number, date: Date, is_paid: boolean, customer: Customer, price: Price, };
