/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BillingCreate,
  BillingInfo,
  BillingInfoWithBalance,
  GetAllBillingInfoParams,
  GetBillingByPropsParams,
} from "../models";

import { fetchMutator } from "../../../utilities/fetch-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetAllBillingInfoUrl = (params?: GetAllBillingInfoParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:9090/billing-info/get-all?${stringifiedParams}`
    : `http://localhost:9090/billing-info/get-all`;
};

export const getAllBillingInfo = async (
  params?: GetAllBillingInfoParams,
  options?: RequestInit,
): Promise<BillingInfo[]> => {
  return fetchMutator<BillingInfo[]>(getGetAllBillingInfoUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAllBillingInfoQueryKey = (
  params?: GetAllBillingInfoParams,
) => {
  return [
    `http://localhost:9090/billing-info/get-all`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAllBillingInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllBillingInfo>>,
  TError = void,
>(
  params?: GetAllBillingInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllBillingInfoQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllBillingInfo>>
  > = ({ signal }) => getAllBillingInfo(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllBillingInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllBillingInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllBillingInfo>>
>;
export type GetAllBillingInfoQueryError = void;

export function useGetAllBillingInfo<
  TData = Awaited<ReturnType<typeof getAllBillingInfo>>,
  TError = void,
>(
  params: undefined | GetAllBillingInfoParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBillingInfo>>,
          TError,
          Awaited<ReturnType<typeof getAllBillingInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBillingInfo<
  TData = Awaited<ReturnType<typeof getAllBillingInfo>>,
  TError = void,
>(
  params?: GetAllBillingInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBillingInfo>>,
          TError,
          Awaited<ReturnType<typeof getAllBillingInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBillingInfo<
  TData = Awaited<ReturnType<typeof getAllBillingInfo>>,
  TError = void,
>(
  params?: GetAllBillingInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllBillingInfo<
  TData = Awaited<ReturnType<typeof getAllBillingInfo>>,
  TError = void,
>(
  params?: GetAllBillingInfoParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllBillingInfoQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getPostCreateBillingUrl = () => {
  return `http://localhost:9090/billing/create`;
};

export const postCreateBilling = async (
  billingCreate: BillingCreate,
  options?: RequestInit,
): Promise<BillingInfo> => {
  return fetchMutator<BillingInfo>(getPostCreateBillingUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(billingCreate),
  });
};

export const getPostCreateBillingMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateBilling>>,
    TError,
    { data: BillingCreate },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateBilling>>,
  TError,
  { data: BillingCreate },
  TContext
> => {
  const mutationKey = ["postCreateBilling"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateBilling>>,
    { data: BillingCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateBilling(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateBillingMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateBilling>>
>;
export type PostCreateBillingMutationBody = BillingCreate;
export type PostCreateBillingMutationError = void;

export const usePostCreateBilling = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateBilling>>,
      TError,
      { data: BillingCreate },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateBilling>>,
  TError,
  { data: BillingCreate },
  TContext
> => {
  return useMutation(getPostCreateBillingMutationOptions(options), queryClient);
};
export const getGetAllBillingUrl = () => {
  return `http://localhost:9090/billing/get-all`;
};

export const getAllBilling = async (
  options?: RequestInit,
): Promise<BillingInfoWithBalance[]> => {
  return fetchMutator<BillingInfoWithBalance[]>(getGetAllBillingUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllBillingQueryKey = () => {
  return [`http://localhost:9090/billing/get-all`] as const;
};

export const getGetAllBillingQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllBilling>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllBillingQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBilling>>> = ({
    signal,
  }) => getAllBilling({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllBilling>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllBillingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllBilling>>
>;
export type GetAllBillingQueryError = void;

export function useGetAllBilling<
  TData = Awaited<ReturnType<typeof getAllBilling>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBilling>>,
          TError,
          Awaited<ReturnType<typeof getAllBilling>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBilling<
  TData = Awaited<ReturnType<typeof getAllBilling>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBilling>>,
          TError,
          Awaited<ReturnType<typeof getAllBilling>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBilling<
  TData = Awaited<ReturnType<typeof getAllBilling>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllBilling<
  TData = Awaited<ReturnType<typeof getAllBilling>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllBillingQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetBillingByPropsUrl = (params?: GetBillingByPropsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:9090/billing/get_by?${stringifiedParams}`
    : `http://localhost:9090/billing/get_by`;
};

export const getBillingByProps = async (
  params?: GetBillingByPropsParams,
  options?: RequestInit,
): Promise<BillingInfoWithBalance[]> => {
  return fetchMutator<BillingInfoWithBalance[]>(
    getGetBillingByPropsUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetBillingByPropsQueryKey = (
  params?: GetBillingByPropsParams,
) => {
  return [
    `http://localhost:9090/billing/get_by`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetBillingByPropsQueryOptions = <
  TData = Awaited<ReturnType<typeof getBillingByProps>>,
  TError = void,
>(
  params?: GetBillingByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetBillingByPropsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getBillingByProps>>
  > = ({ signal }) => getBillingByProps(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getBillingByProps>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBillingByPropsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getBillingByProps>>
>;
export type GetBillingByPropsQueryError = void;

export function useGetBillingByProps<
  TData = Awaited<ReturnType<typeof getBillingByProps>>,
  TError = void,
>(
  params: undefined | GetBillingByPropsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillingByProps>>,
          TError,
          Awaited<ReturnType<typeof getBillingByProps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillingByProps<
  TData = Awaited<ReturnType<typeof getBillingByProps>>,
  TError = void,
>(
  params?: GetBillingByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBillingByProps>>,
          TError,
          Awaited<ReturnType<typeof getBillingByProps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBillingByProps<
  TData = Awaited<ReturnType<typeof getBillingByProps>>,
  TError = void,
>(
  params?: GetBillingByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBillingByProps<
  TData = Awaited<ReturnType<typeof getBillingByProps>>,
  TError = void,
>(
  params?: GetBillingByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetBillingByPropsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
