//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "balance_billing")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub balance_billing_id: i64,
    pub balance_id: i64,
    pub billing_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::balance::Entity",
        from = "Column::BalanceId",
        to = "super::balance::Column::BalanceId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Balance,
    #[sea_orm(
        belongs_to = "super::billing::Entity",
        from = "Column::BillingId",
        to = "super::billing::Column::BillingId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Billing,
}

impl Related<super::balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Balance.def()
    }
}

impl Related<super::billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Billing.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
