//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "billing")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub billing_id: i64,
    pub customer_id: i64,
    pub date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::balance_billing::Entity")]
    BalanceBilling,
    #[sea_orm(has_many = "super::billing_retrieve_data::Entity")]
    BillingRetrieveData,
}

impl Related<super::balance_billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BalanceBilling.def()
    }
}

impl Related<super::billing_retrieve_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillingRetrieveData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
