//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "billing_retrieve_data")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub billing_retrieve_data_id: i64,
    pub billing_id: i64,
    pub retrieve_data_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::billing::Entity",
        from = "Column::BillingId",
        to = "super::billing::Column::BillingId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Billing,
    #[sea_orm(
        belongs_to = "super::retrieve_data::Entity",
        from = "Column::RetrieveDataId",
        to = "super::retrieve_data::Column::RetrieveDataId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RetrieveData,
}

impl Related<super::billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Billing.def()
    }
}

impl Related<super::retrieve_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrieveData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
