//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "customer")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub customer_id: i64,
    pub customer_name: String,
    pub is_active: bool,
    pub is_admin: bool,
    pub created_date: DateTime,
    pub updated_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::balance::Entity")]
    Balance,
    #[sea_orm(has_many = "super::billing::Entity")]
    Billing,
    #[sea_orm(has_many = "super::retrieve_data::Entity")]
    RetrieveData,
}

impl Related<super::balance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Balance.def()
    }
}

impl Related<super::billing::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Billing.def()
    }
}

impl Related<super::retrieve_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrieveData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
