//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "payment_history_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i64,
    pub date: DateTime,
    pub bill_amount: i64,
    pub initial_money: i64,
    pub end_money: i64,
    pub added_money: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user_table::Entity",
        from = "Column::UserId",
        to = "super::user_table::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserTable,
}

impl Related<super::user_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
