//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::hash_password_table::Entity as HashPasswordTable;
pub use super::money_history_table::Entity as MoneyHistoryTable;
pub use super::payment_history_table::Entity as PaymentHistoryTable;
pub use super::price_history_table::Entity as PriceHistoryTable;
pub use super::production_record_table::Entity as ProductionRecordTable;
pub use super::soybean_price_history_table::Entity as SoybeanPriceHistoryTable;
pub use super::taking_record_table::Entity as TakingRecordTable;
pub use super::user_table::Entity as UserTable;
