//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "price")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub price_id: i64,
    pub date: DateTime,
    #[sea_orm(column_type = "Float")]
    pub value: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::retrieve_data::Entity")]
    RetrieveData,
}

impl Related<super::retrieve_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RetrieveData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
