//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "production_record_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTime,
    pub amount: i64,
    pub dreg_price_id: i64,
    pub soybean_price_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::price_history_table::Entity",
        from = "Column::DregPriceId",
        to = "super::price_history_table::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PriceHistoryTable,
    #[sea_orm(
        belongs_to = "super::soybean_price_history_table::Entity",
        from = "Column::SoybeanPriceId",
        to = "super::soybean_price_history_table::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SoybeanPriceHistoryTable,
}

impl Related<super::price_history_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceHistoryTable.def()
    }
}

impl Related<super::soybean_price_history_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SoybeanPriceHistoryTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
