//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "retrieve_data")]
#[serde(rename_all = "camelCase")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub retrieve_data_id: i64,
    pub customer_id: i64,
    pub price_id: i64,
    pub amount: i64,
    pub date: DateTime,
    pub is_paid: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::billing_retrieve_data::Entity")]
    BillingRetrieveData,
    #[sea_orm(
        belongs_to = "super::customer::Entity",
        from = "Column::CustomerId",
        to = "super::customer::Column::CustomerId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Customer,
    #[sea_orm(
        belongs_to = "super::price::Entity",
        from = "Column::PriceId",
        to = "super::price::Column::PriceId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Price,
}

impl Related<super::billing_retrieve_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BillingRetrieveData.def()
    }
}

impl Related<super::customer::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Customer.def()
    }
}

impl Related<super::price::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Price.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
