//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "soybean_price_history_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub date: DateTime,
    pub price: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::production_record_table::Entity")]
    ProductionRecordTable,
}

impl Related<super::production_record_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProductionRecordTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
