//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub username: String,
    pub is_active: bool,
    pub is_admin: bool,
    pub created_date: DateTime,
    pub updated_date: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::money_history_table::Entity")]
    MoneyHistoryTable,
    #[sea_orm(has_many = "super::payment_history_table::Entity")]
    PaymentHistoryTable,
    #[sea_orm(has_many = "super::taking_record_table::Entity")]
    TakingRecordTable,
}

impl Related<super::money_history_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MoneyHistoryTable.def()
    }
}

impl Related<super::payment_history_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PaymentHistoryTable.def()
    }
}

impl Related<super::taking_record_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TakingRecordTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
