//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod money_history_table;
pub mod payment_history_table;
pub mod price_history_table;
pub mod production_record_table;
pub mod soybean_price_history_table;
pub mod taking_record_table;
pub mod user_table;
