//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "taking_record_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: Option<i64>,
    pub price_id: Option<i64>,
    pub amount: Option<i64>,
    pub production_date: Option<DateTime>,
    pub taken_date: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::price_history_table::Entity",
        from = "Column::PriceId",
        to = "super::price_history_table::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PriceHistoryTable,
    #[sea_orm(
        belongs_to = "super::user_table::Entity",
        from = "Column::UserId",
        to = "super::user_table::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserTable,
}

impl Related<super::price_history_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceHistoryTable.def()
    }
}

impl Related<super::user_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
