[package]
name = "ams_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["derive"] }
quote = "1.0"
sea-query = "0.32.1"
convert_case = "0.7.1"
