// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BalanceBillingCreateOrUpdate = { balance_billing_id: number, balance_id: number, billing_id: number, };
