// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";
import type { RetrieveDataWithCustomerAndPrice } from "./RetrieveDataWithCustomerAndPrice";

export type BillingWithRetrieveData = { billing_id: number, customer_id: number, date: Date, customer: Customer, from: Date, to: Date, bill: number, amount: number, retrieves_data: Array<RetrieveDataWithCustomerAndPrice>, };
