// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Customer } from "./Customer";

export type Billing = { billing_id: number, customer_id: number, date: Date, customer: Customer, from: Date, to: Date, bill: number, amount: number, };
