// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProducedDregRecord } from "./ProducedDregRecord";
import type { ProductionRecord } from "./ProductionRecord";
import type { SoyDosageCountRecord } from "./SoyDosageCountRecord";

export type DataRecordValueType = { "Production": ProductionRecord } | { "SoyDosageCount": SoyDosageCountRecord } | { "ProducedDreg": ProducedDregRecord };
