// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RetrieveDataCreateOrUpdate = { retrieve_data_id: number, customer_id: number, price_id: number, amount: number, date: Date, is_paid: boolean, };
