/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import type { Customer } from "./customer";
import type { TransactionType } from "./transactionType";

export type BalanceWithCustomer = {
  balance_id: number;
  changed_value: number;
  customer: Customer;
  customer_id: number;
  date: string;
  transaction_type: TransactionType;
  value: number;
};
