/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import type { RetrieveDataWithCustomerAndPrice } from "./retrieveDataWithCustomerAndPrice";

export type BillingInfo = {
  amount: number;
  bill: number;
  from: string;
  paid_bill: number;
  paid_total_amount: number;
  retrieve_data: RetrieveDataWithCustomerAndPrice[];
  to: string;
  unpaid_bill: number;
  unpaid_total_amount: number;
};
