/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */

export type Customer = {
  created_date: string;
  customer_id: number;
  customer_name: string;
  is_active: boolean;
  is_admin: boolean;
  updated_date: string;
};
