/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  Customer,
  CustomerUpdate,
  DeleteCustomerByCustomerIdPathParameters,
  GetAllCustomerByPropsParams,
  GetCustomerByCustomerIdPathParameters,
  PostCreateCustomerByCustomerNamePathParameters,
} from "../models";

import { fetchMutator } from "../../../utilities/fetch-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPostCreateCustomerByCustomerNameUrl = ({
  customerName,
}: PostCreateCustomerByCustomerNamePathParameters) => {
  return `http://localhost:9090/customer/create/${customerName}`;
};

export const postCreateCustomerByCustomerName = async (
  { customerName }: PostCreateCustomerByCustomerNamePathParameters,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(
    getPostCreateCustomerByCustomerNameUrl({ customerName }),
    {
      ...options,
      method: "POST",
    },
  );
};

export const getPostCreateCustomerByCustomerNameMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
    TError,
    { pathParams: PostCreateCustomerByCustomerNamePathParameters },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
  TError,
  { pathParams: PostCreateCustomerByCustomerNamePathParameters },
  TContext
> => {
  const mutationKey = ["postCreateCustomerByCustomerName"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
    { pathParams: PostCreateCustomerByCustomerNamePathParameters }
  > = (props) => {
    const { pathParams } = props ?? {};

    return postCreateCustomerByCustomerName(pathParams, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateCustomerByCustomerNameMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>
>;

export type PostCreateCustomerByCustomerNameMutationError = void;

export const usePostCreateCustomerByCustomerName = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
      TError,
      { pathParams: PostCreateCustomerByCustomerNamePathParameters },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateCustomerByCustomerName>>,
  TError,
  { pathParams: PostCreateCustomerByCustomerNamePathParameters },
  TContext
> => {
  return useMutation(
    getPostCreateCustomerByCustomerNameMutationOptions(options),
    queryClient,
  );
};
export const getGetAllCustomerByPropsUrl = (
  params?: GetAllCustomerByPropsParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:9090/customer/get_all?${stringifiedParams}`
    : `http://localhost:9090/customer/get_all`;
};

export const getAllCustomerByProps = async (
  params?: GetAllCustomerByPropsParams,
  options?: RequestInit,
): Promise<Customer[]> => {
  return fetchMutator<Customer[]>(getGetAllCustomerByPropsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAllCustomerByPropsQueryKey = (
  params?: GetAllCustomerByPropsParams,
) => {
  return [
    `http://localhost:9090/customer/get_all`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAllCustomerByPropsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllCustomerByProps>>,
  TError = void,
>(
  params?: GetAllCustomerByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomerByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllCustomerByPropsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllCustomerByProps>>
  > = ({ signal }) =>
    getAllCustomerByProps(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllCustomerByProps>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllCustomerByPropsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllCustomerByProps>>
>;
export type GetAllCustomerByPropsQueryError = void;

export function useGetAllCustomerByProps<
  TData = Awaited<ReturnType<typeof getAllCustomerByProps>>,
  TError = void,
>(
  params: undefined | GetAllCustomerByPropsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomerByProps>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomerByProps>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomerByProps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCustomerByProps<
  TData = Awaited<ReturnType<typeof getAllCustomerByProps>>,
  TError = void,
>(
  params?: GetAllCustomerByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomerByProps>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllCustomerByProps>>,
          TError,
          Awaited<ReturnType<typeof getAllCustomerByProps>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllCustomerByProps<
  TData = Awaited<ReturnType<typeof getAllCustomerByProps>>,
  TError = void,
>(
  params?: GetAllCustomerByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomerByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllCustomerByProps<
  TData = Awaited<ReturnType<typeof getAllCustomerByProps>>,
  TError = void,
>(
  params?: GetAllCustomerByPropsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllCustomerByProps>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllCustomerByPropsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getPostUpdateCustomerUrl = () => {
  return `http://localhost:9090/customer/update`;
};

export const postUpdateCustomer = async (
  customerUpdate: CustomerUpdate,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getPostUpdateCustomerUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(customerUpdate),
  });
};

export const getPostUpdateCustomerMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUpdateCustomer>>,
    TError,
    { data: CustomerUpdate },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUpdateCustomer>>,
  TError,
  { data: CustomerUpdate },
  TContext
> => {
  const mutationKey = ["postUpdateCustomer"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUpdateCustomer>>,
    { data: CustomerUpdate }
  > = (props) => {
    const { data } = props ?? {};

    return postUpdateCustomer(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUpdateCustomerMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUpdateCustomer>>
>;
export type PostUpdateCustomerMutationBody = CustomerUpdate;
export type PostUpdateCustomerMutationError = void;

export const usePostUpdateCustomer = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUpdateCustomer>>,
      TError,
      { data: CustomerUpdate },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUpdateCustomer>>,
  TError,
  { data: CustomerUpdate },
  TContext
> => {
  return useMutation(
    getPostUpdateCustomerMutationOptions(options),
    queryClient,
  );
};
export const getGetCustomerByCustomerIdUrl = ({
  customerId,
}: GetCustomerByCustomerIdPathParameters) => {
  return `http://localhost:9090/customer/${customerId}`;
};

export const getCustomerByCustomerId = async (
  { customerId }: GetCustomerByCustomerIdPathParameters,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getGetCustomerByCustomerIdUrl({ customerId }), {
    ...options,
    method: "GET",
  });
};

export const getGetCustomerByCustomerIdQueryKey = ({
  customerId,
}: GetCustomerByCustomerIdPathParameters) => {
  return [`http://localhost:9090/customer/${customerId}`] as const;
};

export const getGetCustomerByCustomerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>,
  TError = void,
>(
  { customerId }: GetCustomerByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCustomerByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetCustomerByCustomerIdQueryKey({ customerId });

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCustomerByCustomerId>>
  > = ({ signal }) =>
    getCustomerByCustomerId({ customerId }, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!customerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCustomerByCustomerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCustomerByCustomerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCustomerByCustomerId>>
>;
export type GetCustomerByCustomerIdQueryError = void;

export function useGetCustomerByCustomerId<
  TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>,
  TError = void,
>(
  pathParams: GetCustomerByCustomerIdPathParameters,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCustomerByCustomerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getCustomerByCustomerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCustomerByCustomerId<
  TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>,
  TError = void,
>(
  pathParams: GetCustomerByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCustomerByCustomerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCustomerByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getCustomerByCustomerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCustomerByCustomerId<
  TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>,
  TError = void,
>(
  pathParams: GetCustomerByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCustomerByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCustomerByCustomerId<
  TData = Awaited<ReturnType<typeof getCustomerByCustomerId>>,
  TError = void,
>(
  { customerId }: GetCustomerByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getCustomerByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCustomerByCustomerIdQueryOptions(
    { customerId },
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getDeleteCustomerByCustomerIdUrl = ({
  customerId,
}: DeleteCustomerByCustomerIdPathParameters) => {
  return `http://localhost:9090/customer/${customerId}`;
};

export const deleteCustomerByCustomerId = async (
  { customerId }: DeleteCustomerByCustomerIdPathParameters,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getDeleteCustomerByCustomerIdUrl({ customerId }), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteCustomerByCustomerIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
    TError,
    { pathParams: DeleteCustomerByCustomerIdPathParameters },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
  TError,
  { pathParams: DeleteCustomerByCustomerIdPathParameters },
  TContext
> => {
  const mutationKey = ["deleteCustomerByCustomerId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
    { pathParams: DeleteCustomerByCustomerIdPathParameters }
  > = (props) => {
    const { pathParams } = props ?? {};

    return deleteCustomerByCustomerId(pathParams, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteCustomerByCustomerIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteCustomerByCustomerId>>
>;

export type DeleteCustomerByCustomerIdMutationError = void;

export const useDeleteCustomerByCustomerId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
      TError,
      { pathParams: DeleteCustomerByCustomerIdPathParameters },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteCustomerByCustomerId>>,
  TError,
  { pathParams: DeleteCustomerByCustomerIdPathParameters },
  TContext
> => {
  return useMutation(
    getDeleteCustomerByCustomerIdMutationOptions(options),
    queryClient,
  );
};
