/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BillingCreate,
  GetAllBillingInfoParams,
  GetBillingByPropsParams
} from '../models';


export type getAllBillingInfoResponse200 = {
  data: void
  status: 200
}

export type getAllBillingInfoResponse404 = {
  data: void
  status: 404
}

export type getAllBillingInfoResponseSuccess = (getAllBillingInfoResponse200) & {
  headers: Headers;
};
export type getAllBillingInfoResponseError = (getAllBillingInfoResponse404) & {
  headers: Headers;
};

export type getAllBillingInfoResponse = (getAllBillingInfoResponseSuccess | getAllBillingInfoResponseError)

export const getGetAllBillingInfoUrl = (params?: GetAllBillingInfoParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/billing-info/get-all?${stringifiedParams}` : `/billing-info/get-all`
}

export const getAllBillingInfo = async (params?: GetAllBillingInfoParams, options?: RequestInit): Promise<getAllBillingInfoResponse> => {

  const res = await fetch(getGetAllBillingInfoUrl(params),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllBillingInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllBillingInfoResponse
}





export const getGetAllBillingInfoQueryKey = (params?: GetAllBillingInfoParams,) => {
  return [
    `/billing-info/get-all`, ...(params ? [params] : [])
  ] as const;
}


export const getGetAllBillingInfoQueryOptions = <TData = Awaited<ReturnType<typeof getAllBillingInfo>>, TError = void>(params?: GetAllBillingInfoParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllBillingInfoQueryKey(params);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBillingInfo>>> = ({ signal }) => getAllBillingInfo(params, { signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBillingInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBillingInfo>>>
export type GetAllBillingInfoQueryError = void


export function useGetAllBillingInfo<TData = Awaited<ReturnType<typeof getAllBillingInfo>>, TError = void>(
  params: undefined | GetAllBillingInfoParams, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        Awaited<ReturnType<typeof getAllBillingInfo>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBillingInfo<TData = Awaited<ReturnType<typeof getAllBillingInfo>>, TError = void>(
  params?: GetAllBillingInfoParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllBillingInfo>>,
        TError,
        Awaited<ReturnType<typeof getAllBillingInfo>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBillingInfo<TData = Awaited<ReturnType<typeof getAllBillingInfo>>, TError = void>(
  params?: GetAllBillingInfoParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllBillingInfo<TData = Awaited<ReturnType<typeof getAllBillingInfo>>, TError = void>(
  params?: GetAllBillingInfoParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBillingInfo>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBillingInfoQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type postCreateBillingResponse200 = {
  data: void
  status: 200
}

export type postCreateBillingResponse404 = {
  data: void
  status: 404
}

export type postCreateBillingResponseSuccess = (postCreateBillingResponse200) & {
  headers: Headers;
};
export type postCreateBillingResponseError = (postCreateBillingResponse404) & {
  headers: Headers;
};

export type postCreateBillingResponse = (postCreateBillingResponseSuccess | postCreateBillingResponseError)

export const getPostCreateBillingUrl = () => {




  return `/billing/create`
}

export const postCreateBilling = async (billingCreate: BillingCreate, options?: RequestInit): Promise<postCreateBillingResponse> => {

  const res = await fetch(getPostCreateBillingUrl(),
    {
      ...options,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', ...options?.headers },
      body: JSON.stringify(
        billingCreate,)
    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postCreateBillingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postCreateBillingResponse
}




export const getPostCreateBillingMutationOptions = <TError = void,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postCreateBilling>>, TError, { data: BillingCreate }, TContext>, fetch?: RequestInit }
  ): UseMutationOptions<Awaited<ReturnType<typeof postCreateBilling>>, TError, { data: BillingCreate }, TContext> => {

  const mutationKey = ['postCreateBilling'];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?
    options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey, }, fetch: undefined };




  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCreateBilling>>, { data: BillingCreate }> = (props) => {
    const { data } = props ?? {};

    return postCreateBilling(data, fetchOptions)
  }






  return { mutationFn, ...mutationOptions }
}

export type PostCreateBillingMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateBilling>>>
export type PostCreateBillingMutationBody = BillingCreate
export type PostCreateBillingMutationError = void

export const usePostCreateBilling = <TError = void,
  TContext = unknown>(options?: { mutation?: UseMutationOptions<Awaited<ReturnType<typeof postCreateBilling>>, TError, { data: BillingCreate }, TContext>, fetch?: RequestInit }
    , queryClient?: QueryClient): UseMutationResult<
      Awaited<ReturnType<typeof postCreateBilling>>,
      TError,
      { data: BillingCreate },
      TContext
    > => {
  return useMutation(getPostCreateBillingMutationOptions(options), queryClient);
}
export type getAllBillingResponse200 = {
  data: void
  status: 200
}

export type getAllBillingResponse404 = {
  data: void
  status: 404
}

export type getAllBillingResponseSuccess = (getAllBillingResponse200) & {
  headers: Headers;
};
export type getAllBillingResponseError = (getAllBillingResponse404) & {
  headers: Headers;
};

export type getAllBillingResponse = (getAllBillingResponseSuccess | getAllBillingResponseError)

export const getGetAllBillingUrl = () => {




  return `/billing/get-all`
}

export const getAllBilling = async (options?: RequestInit): Promise<getAllBillingResponse> => {

  const res = await fetch(getGetAllBillingUrl(),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllBillingResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllBillingResponse
}





export const getGetAllBillingQueryKey = () => {
  return [
    `/billing/get-all`
  ] as const;
}


export const getGetAllBillingQueryOptions = <TData = Awaited<ReturnType<typeof getAllBilling>>, TError = void>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllBillingQueryKey();



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBilling>>> = ({ signal }) => getAllBilling({ signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllBillingQueryResult = NonNullable<Awaited<ReturnType<typeof getAllBilling>>>
export type GetAllBillingQueryError = void


export function useGetAllBilling<TData = Awaited<ReturnType<typeof getAllBilling>>, TError = void>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllBilling>>,
        TError,
        Awaited<ReturnType<typeof getAllBilling>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBilling<TData = Awaited<ReturnType<typeof getAllBilling>>, TError = void>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAllBilling>>,
        TError,
        Awaited<ReturnType<typeof getAllBilling>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllBilling<TData = Awaited<ReturnType<typeof getAllBilling>>, TError = void>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAllBilling<TData = Awaited<ReturnType<typeof getAllBilling>>, TError = void>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllBilling>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllBillingQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type getBillingByPropsResponse200 = {
  data: void
  status: 200
}

export type getBillingByPropsResponse404 = {
  data: void
  status: 404
}

export type getBillingByPropsResponseSuccess = (getBillingByPropsResponse200) & {
  headers: Headers;
};
export type getBillingByPropsResponseError = (getBillingByPropsResponse404) & {
  headers: Headers;
};

export type getBillingByPropsResponse = (getBillingByPropsResponseSuccess | getBillingByPropsResponseError)

export const getGetBillingByPropsUrl = (params?: GetBillingByPropsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/billing/get_by?${stringifiedParams}` : `/billing/get_by`
}

export const getBillingByProps = async (params?: GetBillingByPropsParams, options?: RequestInit): Promise<getBillingByPropsResponse> => {

  const res = await fetch(getGetBillingByPropsUrl(params),
    {
      ...options,
      method: 'GET'


    }
  )

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getBillingByPropsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getBillingByPropsResponse
}





export const getGetBillingByPropsQueryKey = (params?: GetBillingByPropsParams,) => {
  return [
    `/billing/get_by`, ...(params ? [params] : [])
  ] as const;
}


export const getGetBillingByPropsQueryOptions = <TData = Awaited<ReturnType<typeof getBillingByProps>>, TError = void>(params?: GetBillingByPropsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData>>, fetch?: RequestInit }
) => {

  const { query: queryOptions, fetch: fetchOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBillingByPropsQueryKey(params);



  const queryFn: QueryFunction<Awaited<ReturnType<typeof getBillingByProps>>> = ({ signal }) => getBillingByProps(params, { signal, ...fetchOptions });





  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBillingByPropsQueryResult = NonNullable<Awaited<ReturnType<typeof getBillingByProps>>>
export type GetBillingByPropsQueryError = void


export function useGetBillingByProps<TData = Awaited<ReturnType<typeof getBillingByProps>>, TError = void>(
  params: undefined | GetBillingByPropsParams, options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData>> & Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        Awaited<ReturnType<typeof getBillingByProps>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBillingByProps<TData = Awaited<ReturnType<typeof getBillingByProps>>, TError = void>(
  params?: GetBillingByPropsParams, options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData>> & Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getBillingByProps>>,
        TError,
        Awaited<ReturnType<typeof getBillingByProps>>
      >, 'initialData'
    >, fetch?: RequestInit
  }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBillingByProps<TData = Awaited<ReturnType<typeof getBillingByProps>>, TError = void>(
  params?: GetBillingByPropsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBillingByProps<TData = Awaited<ReturnType<typeof getBillingByProps>>, TError = void>(
  params?: GetBillingByPropsParams, options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getBillingByProps>>, TError, TData>>, fetch?: RequestInit }
  , queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBillingByPropsQueryOptions(params, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




