// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TransactionType } from "./TransactionType";

export type BalanceCreateOrUpdate = { balance_id: number, customer_id: number, value: number, changed_value: number, date: Date, transaction_type: TransactionType, };
