// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Balance } from "./Balance";
import type { Billing } from "./Billing";

export type BalanceBilling = { balance_billing_id: number, balance_id: number, billing_id: number, balance: Balance, billing: Billing, };
