// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RetrieveDataWithCustomerAndPrice } from "./RetrieveDataWithCustomerAndPrice";

export type BillingInfo = { from: Date, to: Date, retrieve_data: Array<RetrieveDataWithCustomerAndPrice>, bill: number, amount: number, };
