// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Billing = { billing_id: number, customer_id: number, date: Date, customer: Date, from: Date, to: Date, bill: number, amount: number, };
