/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeletePriceByIdPathParameters,
  Price,
  UpdatePricePathParameters,
} from "../models";

import { fetchMutator } from "../../../utilities/fetch-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getGetAllPriceUrl = () => {
  return `http://localhost:9090/price/get-all`;
};

export const getAllPrice = async (options?: RequestInit): Promise<Price[]> => {
  return fetchMutator<Price[]>(getGetAllPriceUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAllPriceQueryKey = () => {
  return [`http://localhost:9090/price/get-all`] as const;
};

export const getGetAllPriceQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllPrice>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllPrice>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllPriceQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllPrice>>> = ({
    signal,
  }) => getAllPrice({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllPrice>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllPriceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllPrice>>
>;
export type GetAllPriceQueryError = void;

export function useGetAllPrice<
  TData = Awaited<ReturnType<typeof getAllPrice>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPrice>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPrice>>,
          TError,
          Awaited<ReturnType<typeof getAllPrice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllPrice<
  TData = Awaited<ReturnType<typeof getAllPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPrice>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllPrice>>,
          TError,
          Awaited<ReturnType<typeof getAllPrice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllPrice<
  TData = Awaited<ReturnType<typeof getAllPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPrice>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllPrice<
  TData = Awaited<ReturnType<typeof getAllPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllPrice>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllPriceQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetLatestPriceUrl = () => {
  return `http://localhost:9090/price/get-latest`;
};

export const getLatestPrice = async (options?: RequestInit): Promise<Price> => {
  return fetchMutator<Price>(getGetLatestPriceUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetLatestPriceQueryKey = () => {
  return [`http://localhost:9090/price/get-latest`] as const;
};

export const getGetLatestPriceQueryOptions = <
  TData = Awaited<ReturnType<typeof getLatestPrice>>,
  TError = void,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getLatestPrice>>, TError, TData>
  >;
  request?: SecondParameter<typeof fetchMutator>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetLatestPriceQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getLatestPrice>>> = ({
    signal,
  }) => getLatestPrice({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getLatestPrice>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLatestPriceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLatestPrice>>
>;
export type GetLatestPriceQueryError = void;

export function useGetLatestPrice<
  TData = Awaited<ReturnType<typeof getLatestPrice>>,
  TError = void,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatestPrice>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestPrice>>,
          TError,
          Awaited<ReturnType<typeof getLatestPrice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatestPrice<
  TData = Awaited<ReturnType<typeof getLatestPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatestPrice>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestPrice>>,
          TError,
          Awaited<ReturnType<typeof getLatestPrice>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatestPrice<
  TData = Awaited<ReturnType<typeof getLatestPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatestPrice>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetLatestPrice<
  TData = Awaited<ReturnType<typeof getLatestPrice>>,
  TError = void,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getLatestPrice>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLatestPriceQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getUpdatePriceUrl = ({ newPrice }: UpdatePricePathParameters) => {
  return `http://localhost:9090/price/update/${newPrice}`;
};

export const updatePrice = async (
  { newPrice }: UpdatePricePathParameters,
  options?: RequestInit,
): Promise<number> => {
  return fetchMutator<number>(getUpdatePriceUrl({ newPrice }), {
    ...options,
    method: "POST",
  });
};

export const getUpdatePriceMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updatePrice>>,
    TError,
    { pathParams: UpdatePricePathParameters },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updatePrice>>,
  TError,
  { pathParams: UpdatePricePathParameters },
  TContext
> => {
  const mutationKey = ["updatePrice"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updatePrice>>,
    { pathParams: UpdatePricePathParameters }
  > = (props) => {
    const { pathParams } = props ?? {};

    return updatePrice(pathParams, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdatePriceMutationResult = NonNullable<
  Awaited<ReturnType<typeof updatePrice>>
>;

export type UpdatePriceMutationError = void;

export const useUpdatePrice = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updatePrice>>,
      TError,
      { pathParams: UpdatePricePathParameters },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updatePrice>>,
  TError,
  { pathParams: UpdatePricePathParameters },
  TContext
> => {
  return useMutation(getUpdatePriceMutationOptions(options), queryClient);
};
export const getDeletePriceByIdUrl = ({
  priceId,
}: DeletePriceByIdPathParameters) => {
  return `http://localhost:9090/price/${priceId}`;
};

export const deletePriceById = async (
  { priceId }: DeletePriceByIdPathParameters,
  options?: RequestInit,
): Promise<number> => {
  return fetchMutator<number>(getDeletePriceByIdUrl({ priceId }), {
    ...options,
    method: "DELETE",
  });
};

export const getDeletePriceByIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deletePriceById>>,
    TError,
    { pathParams: DeletePriceByIdPathParameters },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deletePriceById>>,
  TError,
  { pathParams: DeletePriceByIdPathParameters },
  TContext
> => {
  const mutationKey = ["deletePriceById"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deletePriceById>>,
    { pathParams: DeletePriceByIdPathParameters }
  > = (props) => {
    const { pathParams } = props ?? {};

    return deletePriceById(pathParams, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeletePriceByIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deletePriceById>>
>;

export type DeletePriceByIdMutationError = void;

export const useDeletePriceById = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deletePriceById>>,
      TError,
      { pathParams: DeletePriceByIdPathParameters },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deletePriceById>>,
  TError,
  { pathParams: DeletePriceByIdPathParameters },
  TContext
> => {
  return useMutation(getDeletePriceByIdMutationOptions(options), queryClient);
};
