/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteRetrieveDataByRetrieveDataIdPathParameters,
  GetAllRetrieveDataParams,
  RetrieveDataCreate,
  RetrieveDataCreateOrUpdate,
  RetrieveDataCreateWithDate,
  RetrieveDataWithCustomerAndPrice,
} from "../models";

import { fetchMutator } from "../../../utilities/fetch-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPostCreateRetrieveDataUrl = () => {
  return `http://localhost:9090/retrieve-data/create`;
};

export const postCreateRetrieveData = async (
  retrieveDataCreate: RetrieveDataCreate,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getPostCreateRetrieveDataUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(retrieveDataCreate),
  });
};

export const getPostCreateRetrieveDataMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateRetrieveData>>,
    TError,
    { data: RetrieveDataCreate },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateRetrieveData>>,
  TError,
  { data: RetrieveDataCreate },
  TContext
> => {
  const mutationKey = ["postCreateRetrieveData"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateRetrieveData>>,
    { data: RetrieveDataCreate }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateRetrieveData(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateRetrieveDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateRetrieveData>>
>;
export type PostCreateRetrieveDataMutationBody = RetrieveDataCreate;
export type PostCreateRetrieveDataMutationError = void;

export const usePostCreateRetrieveData = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateRetrieveData>>,
      TError,
      { data: RetrieveDataCreate },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateRetrieveData>>,
  TError,
  { data: RetrieveDataCreate },
  TContext
> => {
  return useMutation(
    getPostCreateRetrieveDataMutationOptions(options),
    queryClient,
  );
};
export const getPostCreateRetrieveDataWithDateUrl = () => {
  return `http://localhost:9090/retrieve-data/create-with-date`;
};

export const postCreateRetrieveDataWithDate = async (
  retrieveDataCreateWithDate: RetrieveDataCreateWithDate,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getPostCreateRetrieveDataWithDateUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(retrieveDataCreateWithDate),
  });
};

export const getPostCreateRetrieveDataWithDateMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>,
    TError,
    { data: RetrieveDataCreateWithDate },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>,
  TError,
  { data: RetrieveDataCreateWithDate },
  TContext
> => {
  const mutationKey = ["postCreateRetrieveDataWithDate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>,
    { data: RetrieveDataCreateWithDate }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateRetrieveDataWithDate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateRetrieveDataWithDateMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>
>;
export type PostCreateRetrieveDataWithDateMutationBody =
  RetrieveDataCreateWithDate;
export type PostCreateRetrieveDataWithDateMutationError = void;

export const usePostCreateRetrieveDataWithDate = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>,
      TError,
      { data: RetrieveDataCreateWithDate },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateRetrieveDataWithDate>>,
  TError,
  { data: RetrieveDataCreateWithDate },
  TContext
> => {
  return useMutation(
    getPostCreateRetrieveDataWithDateMutationOptions(options),
    queryClient,
  );
};
export const getDeleteRetrieveDataByRetrieveDataIdUrl = ({
  retrieveDataId,
}: DeleteRetrieveDataByRetrieveDataIdPathParameters) => {
  return `http://localhost:9090/retrieve-data/delete/${retrieveDataId}`;
};

export const deleteRetrieveDataByRetrieveDataId = async (
  { retrieveDataId }: DeleteRetrieveDataByRetrieveDataIdPathParameters,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(
    getDeleteRetrieveDataByRetrieveDataIdUrl({ retrieveDataId }),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteRetrieveDataByRetrieveDataIdMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>,
    TError,
    { pathParams: DeleteRetrieveDataByRetrieveDataIdPathParameters },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>,
  TError,
  { pathParams: DeleteRetrieveDataByRetrieveDataIdPathParameters },
  TContext
> => {
  const mutationKey = ["deleteRetrieveDataByRetrieveDataId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>,
    { pathParams: DeleteRetrieveDataByRetrieveDataIdPathParameters }
  > = (props) => {
    const { pathParams } = props ?? {};

    return deleteRetrieveDataByRetrieveDataId(pathParams, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteRetrieveDataByRetrieveDataIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>
>;

export type DeleteRetrieveDataByRetrieveDataIdMutationError = void;

export const useDeleteRetrieveDataByRetrieveDataId = <
  TError = void,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>,
      TError,
      { pathParams: DeleteRetrieveDataByRetrieveDataIdPathParameters },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteRetrieveDataByRetrieveDataId>>,
  TError,
  { pathParams: DeleteRetrieveDataByRetrieveDataIdPathParameters },
  TContext
> => {
  return useMutation(
    getDeleteRetrieveDataByRetrieveDataIdMutationOptions(options),
    queryClient,
  );
};
export const getGetAllRetrieveDataUrl = (params?: GetAllRetrieveDataParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:9090/retrieve-data/get-all?${stringifiedParams}`
    : `http://localhost:9090/retrieve-data/get-all`;
};

export const getAllRetrieveData = async (
  params?: GetAllRetrieveDataParams,
  options?: RequestInit,
): Promise<RetrieveDataWithCustomerAndPrice[]> => {
  return fetchMutator<RetrieveDataWithCustomerAndPrice[]>(
    getGetAllRetrieveDataUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetAllRetrieveDataQueryKey = (
  params?: GetAllRetrieveDataParams,
) => {
  return [
    `http://localhost:9090/retrieve-data/get-all`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAllRetrieveDataQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllRetrieveData>>,
  TError = void,
>(
  params?: GetAllRetrieveDataParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRetrieveData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAllRetrieveDataQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAllRetrieveData>>
  > = ({ signal }) => getAllRetrieveData(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllRetrieveData>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllRetrieveDataQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllRetrieveData>>
>;
export type GetAllRetrieveDataQueryError = void;

export function useGetAllRetrieveData<
  TData = Awaited<ReturnType<typeof getAllRetrieveData>>,
  TError = void,
>(
  params: undefined | GetAllRetrieveDataParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRetrieveData>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRetrieveData>>,
          TError,
          Awaited<ReturnType<typeof getAllRetrieveData>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllRetrieveData<
  TData = Awaited<ReturnType<typeof getAllRetrieveData>>,
  TError = void,
>(
  params?: GetAllRetrieveDataParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRetrieveData>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllRetrieveData>>,
          TError,
          Awaited<ReturnType<typeof getAllRetrieveData>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllRetrieveData<
  TData = Awaited<ReturnType<typeof getAllRetrieveData>>,
  TError = void,
>(
  params?: GetAllRetrieveDataParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRetrieveData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllRetrieveData<
  TData = Awaited<ReturnType<typeof getAllRetrieveData>>,
  TError = void,
>(
  params?: GetAllRetrieveDataParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getAllRetrieveData>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllRetrieveDataQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getPostUpdateRetrieveDataUrl = () => {
  return `http://localhost:9090/retrieve-data/update`;
};

export const postUpdateRetrieveData = async (
  retrieveDataCreateOrUpdate: RetrieveDataCreateOrUpdate,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getPostUpdateRetrieveDataUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(retrieveDataCreateOrUpdate),
  });
};

export const getPostUpdateRetrieveDataMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postUpdateRetrieveData>>,
    TError,
    { data: RetrieveDataCreateOrUpdate },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postUpdateRetrieveData>>,
  TError,
  { data: RetrieveDataCreateOrUpdate },
  TContext
> => {
  const mutationKey = ["postUpdateRetrieveData"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUpdateRetrieveData>>,
    { data: RetrieveDataCreateOrUpdate }
  > = (props) => {
    const { data } = props ?? {};

    return postUpdateRetrieveData(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostUpdateRetrieveDataMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUpdateRetrieveData>>
>;
export type PostUpdateRetrieveDataMutationBody = RetrieveDataCreateOrUpdate;
export type PostUpdateRetrieveDataMutationError = void;

export const usePostUpdateRetrieveData = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postUpdateRetrieveData>>,
      TError,
      { data: RetrieveDataCreateOrUpdate },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postUpdateRetrieveData>>,
  TError,
  { data: RetrieveDataCreateOrUpdate },
  TContext
> => {
  return useMutation(
    getPostUpdateRetrieveDataMutationOptions(options),
    queryClient,
  );
};
