/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * AMS API
 * 🥔 AMS - Ampas Management System.
 * OpenAPI spec version: 0.0.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  BalanceCreateOrUpdateWithoutChangedValue,
  GetAllBalanceParams,
  GetLatestBalanceByCustomerIdPathParameters,
} from "../models";

import { fetchMutator } from "../../../utilities/fetch-mutator";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getPostCreateBalanceUrl = () => {
  return `http://localhost:9090/balance`;
};

export const postCreateBalance = async (
  balanceCreateOrUpdateWithoutChangedValue: BalanceCreateOrUpdateWithoutChangedValue,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getPostCreateBalanceUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(balanceCreateOrUpdateWithoutChangedValue),
  });
};

export const getPostCreateBalanceMutationOptions = <
  TError = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postCreateBalance>>,
    TError,
    { data: BalanceCreateOrUpdateWithoutChangedValue },
    TContext
  >;
  request?: SecondParameter<typeof fetchMutator>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postCreateBalance>>,
  TError,
  { data: BalanceCreateOrUpdateWithoutChangedValue },
  TContext
> => {
  const mutationKey = ["postCreateBalance"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postCreateBalance>>,
    { data: BalanceCreateOrUpdateWithoutChangedValue }
  > = (props) => {
    const { data } = props ?? {};

    return postCreateBalance(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostCreateBalanceMutationResult = NonNullable<
  Awaited<ReturnType<typeof postCreateBalance>>
>;
export type PostCreateBalanceMutationBody =
  BalanceCreateOrUpdateWithoutChangedValue;
export type PostCreateBalanceMutationError = void;

export const usePostCreateBalance = <TError = void, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postCreateBalance>>,
      TError,
      { data: BalanceCreateOrUpdateWithoutChangedValue },
      TContext
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postCreateBalance>>,
  TError,
  { data: BalanceCreateOrUpdateWithoutChangedValue },
  TContext
> => {
  return useMutation(getPostCreateBalanceMutationOptions(options), queryClient);
};
export const getGetAllBalanceUrl = (params?: GetAllBalanceParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:9090/balance/get-all?${stringifiedParams}`
    : `http://localhost:9090/balance/get-all`;
};

export const getAllBalance = async (
  params?: GetAllBalanceParams,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(getGetAllBalanceUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetAllBalanceQueryKey = (params?: GetAllBalanceParams) => {
  return [
    `http://localhost:9090/balance/get-all`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetAllBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllBalance>>,
  TError = void,
>(
  params?: GetAllBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAllBalanceQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllBalance>>> = ({
    signal,
  }) => getAllBalance(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAllBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllBalance>>
>;
export type GetAllBalanceQueryError = void;

export function useGetAllBalance<
  TData = Awaited<ReturnType<typeof getAllBalance>>,
  TError = void,
>(
  params: undefined | GetAllBalanceParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBalance>>,
          TError,
          Awaited<ReturnType<typeof getAllBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBalance<
  TData = Awaited<ReturnType<typeof getAllBalance>>,
  TError = void,
>(
  params?: GetAllBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllBalance>>,
          TError,
          Awaited<ReturnType<typeof getAllBalance>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAllBalance<
  TData = Awaited<ReturnType<typeof getAllBalance>>,
  TError = void,
>(
  params?: GetAllBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAllBalance<
  TData = Awaited<ReturnType<typeof getAllBalance>>,
  TError = void,
>(
  params?: GetAllBalanceParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllBalance>>, TError, TData>
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllBalanceQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetLatestBalanceByCustomerIdUrl = ({
  customerId,
}: GetLatestBalanceByCustomerIdPathParameters) => {
  return `http://localhost:9090/balance/latest/${customerId}`;
};

export const getLatestBalanceByCustomerId = async (
  { customerId }: GetLatestBalanceByCustomerIdPathParameters,
  options?: RequestInit,
): Promise<void> => {
  return fetchMutator<void>(
    getGetLatestBalanceByCustomerIdUrl({ customerId }),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetLatestBalanceByCustomerIdQueryKey = ({
  customerId,
}: GetLatestBalanceByCustomerIdPathParameters) => {
  return [`http://localhost:9090/balance/latest/${customerId}`] as const;
};

export const getGetLatestBalanceByCustomerIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
  TError = void,
>(
  { customerId }: GetLatestBalanceByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetLatestBalanceByCustomerIdQueryKey({ customerId });

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
  > = ({ signal }) =>
    getLatestBalanceByCustomerId({ customerId }, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!customerId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetLatestBalanceByCustomerIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
>;
export type GetLatestBalanceByCustomerIdQueryError = void;

export function useGetLatestBalanceByCustomerId<
  TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
  TError = void,
>(
  pathParams: GetLatestBalanceByCustomerIdPathParameters,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatestBalanceByCustomerId<
  TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
  TError = void,
>(
  pathParams: GetLatestBalanceByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
          TError,
          Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetLatestBalanceByCustomerId<
  TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
  TError = void,
>(
  pathParams: GetLatestBalanceByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetLatestBalanceByCustomerId<
  TData = Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
  TError = void,
>(
  { customerId }: GetLatestBalanceByCustomerIdPathParameters,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getLatestBalanceByCustomerId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof fetchMutator>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetLatestBalanceByCustomerIdQueryOptions(
    { customerId },
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
